### ISSUE TITLE
Add code coverage reporting to CI flow

### ISSUE THREAD

**Issue by justinmayer** [justinmayer/kagi#20]
We are using continuous integration to ensure future PRs don't fail our test suite, but we should also ensure our CI flow checks and reports on PR test coverage. (Refs #11 #12)

Related links:
* https://circleci.com/blog/making-code-coverage-easy-to-see-with-the-codecov-orb/
* https://github.com/strawberry-graphql/strawberry/commit/e2b2a813257db23845afc1f4b7f2c09236cbe15c

**Comment by Natim** [comment]
Right now the current CI tests fail if the coverage is not 100%.

**Comment by justinmayer** [comment]
Ah, I obviously didn’t realize that. What mechanism provides that exactly?

**Comment by Natim** [comment]
```https://github.com/justinmayer/kagi/blob/master/Makefile#L23-L24```

**Comment by Natim** [comment]
Handled with #11
