### ISSUE TITLE
Consider switching from Make to Invoke

### ISSUE THREAD

**Issue by justinmayer** [justinmayer/kagi#24]
Makefiles can get rather complicated, with somewhat arcane and cumbersome syntax. Would we be better off switching to [Invoke](https://github.com/pyinvoke/invoke), which would allow us to reason in Python?

**Comment by justinmayer** [comment]
After spending some time researching this topic, I find myself with some unanswered questions regarding the goals for this kind of automation…

1. What is more important: making things easier for intermediate developers or beginners?
2. What is more important: long-term readability and maintainability, or fewest number of commands for beginners to get started?
3. How much do we care about Windows users? (`Make` is not easy to use on Windows.)
4. What is the **most number of commands** we should target for beginners to bootstrap the project?

Python projects in general involve a number of bootstrapping steps that are hard to minimize. Solutions for this that are generally considered to be universal — such as Bash scripts and Makefiles — are usually not well-supported on Windows.

There are many dependency problems, where one thing requires something else. For example, virtual environments. Can and should we assume beginners who are embarking on adding WebAuthn-based multi-factor authentication to a Django project will know how to handle creating and activating virtual environments? If not, will this automation need to handle virtual environment creation/activation?

One possible approach could be to use Poetry to automatically handle virtual environments on behalf of beginners. Steps for that scenario might look like:

1. `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python`
2. `git clone [...] && cd kagi`
3. `poetry install`
4. `invoke setup`

Beginners on POSIX systems such as macOS and Linux could benefit from Make since it's pre-installed, and thus there's one less step involved compared to Invoke. But [my experience with Pelican](https://github.com/getpelican/pelican/issues/2443) indicates that, for Windows users, Make isn't readily available and is actually harder to use than Python-based tooling. Moreover, personally I find it challenging to parse Makefile syntax. There are multiple places in the existing Makefile where I have no idea what a particular invocation is doing. That's clearly due to my inexperience with Make and not the fault of Make or the existing Makefile, of course! I'm only pointing out that presently I'm not in a position to really contribute to the current Make-based automation.

So… Are four steps are too many? 😅

Any other thoughts on this topic? I am truly open to any and all suggestions.

**Comment by Natim** [comment]
If I am not mistaken, Windows last version ships with an unix like shell that supports make out of the box.

**Comment by justinmayer** [comment]
I suppose that's true as of a few months ago, so perhaps that particular concern is not as much of a problem as it once was.

Since I spent some time working on it, I submitted pull request #27, mainly so you could give it a spin and let me know what you think. As I mentioned previously, this isn't something I feel strongly about. But the live browser-reload feature I added for previewing Sphinx documentation builds is pretty cool. :wink:

**Comment by Natim** [comment]
It is indeed much more readable. I <3 python
